### DISCUSSION TITLE
Help?

### DISCUSSION THREAD

**Discussion by notsomot** [autoSteve/acMqtt#22] [General]
Heya, 
Would someone be interested in walking me through this, please? I have got to a point, im not going anywhere - looking for someone to assist with fault finding and remote login to see what I have done wrong. 

Can see the CBus, the home assistant, but getting errors 
Resident script:43: attempt to index global 'event' (a nil value)
stack traceback:

**Comment by autoSteve** [comment]
Which script is that, @notsomot? I've a thinking that it is the script "MQTT final", going by the line number.

That looks for all the world like the _event_ script _MQTT final_ is installed as a _resident_ script. That's not right. If that were installed as a resident then you'd get an error like that, because the in-built table "event" would not exist in a resident.

It needs to be an event script, set to not execute during ramping, and tied to the group address / keyword _MQTT_.

**Comment by notsomot** [comment]
Thanks for the prompt reply @autoSteve. 

Have moved the script and getting a similar error 
First real-time doing something of this level, so fumbling around abit. 
Might look at removing the scripts on the 5500SHAC and starting again, might have missed something. 

Also, was unsure what yaml to edit, so have tried a few different places with limited success. 

When I use the MQTT expolorer, I can see the homeassistant and the CBUS. I can send the CBUS commands via the HA. But they arent talking to each other naturally. 

If someone was able to spend an hour or two with me, teaching me, would be happy to pay.

**Comment by notsomot** [comment]
Hi Steve, 

Library cbuslogic:0: Unable to find network tag '0/56/3'
stack traceback:
 [C]: in function 'error'
 Library cbuslogic: in function 'CBusLookupTags'
 Library cbuslogic: in function '_GetCBusLightData'
 Library cbuslogic: in function 'GetCBusLevel'
 Common functions:2: in main chunk

Got a new error this time, guess that is progress. 

Do I tag the objects in the CBUS objects list with the tag MQTT?

**Comment by autoSteve** [comment]
I suggest reading the README to get a handle on exactly what to do. For CBus sync, you need to install the following two scripts only:

- MQTT send receive: As a resident/zero sleep.
- MQTT Final: As an event-based, fire on keyword MQTT, do not execute during ramping

Then set up keywords for objects in the SHAC that you want to sync with HA, which is documented in the README.

MQTT Final is only applicable for firmware 1.15.0+. If using less than this then upgrade, or see the README about using "MQTT" event-based instead.

The resident script "Heartbeat", and everything else is optional. The yaml files in acMQTT are examples for using ESPHome IoT devices, which you probably don't need. The other yaml that might want editing is /homeassistant/configuration.yaml in HA to set up things like Google Assistant.

There are examples for how to set up keywords in the README. At the most basic, for lighting objects all that is needed is the keyword "MQTT", with the additional keyword "light" being the default type. Other keywords exist for many things, like switch, sensor and more. Also keywords like "pn=My desired name" to use a name other than the SHAC object name, and "sa=Kitchen" for suggested area.

So, for example:
MQTT, light, sa=Kitchen, pn=Main Light

Or:
MQTT, switch, sa=Kitchen, pn=Toaster

Tagging with these keywords does two things. Firstly it allows HA discovery topics to be automatically built. Secondly it allows the MQTT Final script to fire when object values change in CBus, which causes MQTT send receive to send the value to the Mosquitto broker, which HA then picks up.

For the error, post a screen clip of what your objects look like.

**Comment by autoSteve** [comment]
Here's what some of my objects are set up like:

<img width="2329" alt="image" src="https://github.com/autoSteve/acMqtt/assets/37229860/7c748581-6898-4d5c-9bbf-119f22e9b665">

**Reply by notsomot** [reply]
That is extremely helpful, thankyou. Adding keywords in now, have gone over the README and adding the scripts in again, slowly. 

Will give it another go, thankyou so much for your help.

**Comment by notsomot** [comment]
Hi @autoSteve 
Are you able to send a screenshot of the confirgeration.yaml looks like?
I have stopped getting errors on the cbus now, but am getting timelouts on the home assistant. Thinking I am getting closer. 

Do I just put this in the configeration.yaml ?


<img width="497" alt="Screenshot 2024-01-15 at 2 07 57 pm" src="https://github.com/autoSteve/acMqtt/assets/7407581/d72539a2-34e0-45c9-925f-804e3402f52f">

**Comment by autoSteve** [comment]
This is the exact content of mine. I use Nabu Casa HA Cloud, hence the Google assistant settings.

What sort of HA timeouts?

```
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
#  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.10.0/24

mqtt:
#  client_id: haos
#  keepalive: 20

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

cloud:
  google_actions:
    filter:
      include_domains:
        - switch
#        - alarm_control_panel
        - binary_sensor
        - button
        - camera
        - climate
        - cover
        - fan
        - group
        - input_boolean
        - input_select
        - light
        - lock
#        - media_player
        - scene
        - script
        - sensor
        - switch
        - vacuum

automation: !include automations.yaml
#   !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
```
