### DISCUSSION TITLE
Advice on using Somfy Blinds as a 'cover' entity in HA

### DISCUSSION THREAD

**Discussion by pbyrne-ms** [autoSteve/acMqtt#56] [Q&A] [answered]
G’Day Steve! Hope all is well with you. Still loving and using your ‘acMqtt’ project 😊.
Also congrats on getting involved on the solcast HA integration, I love that also, and am an avid user. You are a busy man!

Looking to pick your brain on how to go about changing the way I have integrated some Somfy blinds. I currently have them set up with the object keywords like ‘MQTT, select, sa=Living Room, img=mdi:blinds, lvl=Close:0/Favourite:1/Stop:5/Open:255’, and this works great, I have buttons in HA that can set the select level as I need it, all works. My next bright idea was to expose them to Alexa using the [do-it-yourself](https://www.home-assistant.io/integrations/alexa.smart_home/) method. I should also state my Alexa integration works perfectly fine for most things already, lights, buttons, switches yada yada. The crux of it is I can’t expose my ‘select’ entities to Alexa, this integration doesn’t seem to support them.
But it does support ‘cover’, which is probably how I should have done it…. 

My reluctance at the time was these Somfy units generally use 4 levels – 0,5&255 like a typical C-Bus shutter/blind relay, but they also have an additional level of “1” which is like a favourite or preset position. You just manually set your ‘favourite’ position on the blind itself with its own remote. As far as the C-Bus integration goes, you just set the object/level to 1 and it all works fine. Also, I can ‘only’ use the level presets with my blinds, I can’t use them like a slider and just drive them to wherever I want from 0-100% etc.

I had a quick look over the lua code in ‘MQTT send receive.lua’ (which admittedly is now so good and efficient it is surpassing my amateur sleuth abilities!) but I can’t see how the current ‘cover’ config can work for these things that need 4 presets.
Of the 3 ways it currently works, none of them seem to fit the bill…

Any advice?

**Comment by autoSteve** [comment, marked as answer]
G'day Paddy. Long time! (Thanks, BTW.)

Alexa not supporting input_select is a bummer. But maybe there is a way around this.

As a test, what if you set up some templated boolean or switch entities in HA that when fired run an automation to set the desired select entity level for a blind? That way you could keep the select, the HA UI and your favourites even though Alexa doesn't grok that.

This wouldn't be so bad for a small number of blinds. It would be a pain if every room in your house was wired for, "Can't be arsed to get off me bum and open a blind manually..."

> I have buttons

What's behind the buttons? Are they already templated things that fire automations to set the select? Can those be exposed to Alexa?

> surpassing my amateur sleuth abilities

🤣 Sounds like you sleuthed just fine.

**Reply by pbyrne-ms** [reply]
Hey! thanks for that, you managed to engage my brain to 'try harder' :) I need to setup some fake templated covers in HA, like this maybe, https://www.home-assistant.io/integrations/cover.template/ , and just twiddle the actions to set my existing 'select' entitys... I have 15 blinds, but if I get one to work it's just copy/paste really, so not a big deal...

The 'buttons' I mentioned was probably poorly phrased, they are actually mushroom entity cards, so just UI things really. But those cards have the ability to set select items to a specific number when you click them, by using a 'select.select_option' service call ... so at the time that 'worked-for-me' , and then clearly I stopped bothering to find a better way :)

And thinking about it, that's all I need to do in the fake templated covers.... Ok, that's this weekends distraction sorted so!

Thanks again, go well!

**Reply by autoSteve** [reply]
How'd you go, @pbyrne-ms? Good weekend project?

**Comment by pbyrne-ms** [comment]
Hey Steve, yes, I'm calling it a success! For anyone else that may read this, these are Somfy blinds controlled via RTS radio codes, achieved by connecting a 'Somfy RS485 RTS Transmitter' to a SHAC/NAC and sending it various commands via LUA code. They are NOT standard hardwired blinds controlled by C-Bus shutter/blind relays. The details behind all that are not relevant to this conversation really, but just mentioned for context. In C-Bus/Toolkit, each blind is simply assigned to a group, and this group has 4 levels associated with it, to control the blind (0,1,5&255). In the SHAC/NAC, if you apply the keywords ‘MQTT, select, sa=My Blind, img=mdi:blinds, lvl=Close:0/Favourite:1/Stop:5/Open:255’ to it, Steves acMqtt code will automatically expose it to home assistant (As a 'select' entity). To convert this to a 'cover' in homeassistant, which you can then expose to Alexa/Homekit etc, you can use the following YAML example in your 'configuration.yaml' file


```
#Virtual Covers, compatible with Somfy blinds controlled with RTS via SHAC LUA integration

cover:
  - platform: template
    covers:
      ## Define all blinds below here
      my_cover_entity_name:
        device_class: blind
        unique_id: 29d7d898-4c47-45e7-b530-2b33386393d4 # (change/regenerate this, per blind)
        optimistic: false
        friendly_name: "My Blind"
        value_template: >-
                        {% if is_state('input_select.my_blind_4pos_selector', 'Close') %}
                        closing
                        {% elif is_state('input_select.my_blind_4pos_selector', 'Open') %}
                        opening
                        {% endif %}
        position_template: >-
                        {% if is_state('input_select.my_blind_4pos_selector', 'Close') %}
                        0
                        {% elif is_state('input_select.my_blind_4pos_selector', 'Favourite') %}
                        50
                        {% elif is_state('input_select.my_blind_4pos_selector', 'Stop') %}
                        none # sets 'unknown' as the feedback in HA
                        {% elif is_state('input_select.my_blind_4pos_selector', 'Open') %}
                        100
                        {% endif %}
        open_cover:
          action: input_select.select_option
          target:
            entity_id: input_select.my_blind_4pos_selector
          data:
              option: "Open" # 255
        close_cover:
          action: input_select.select_option
          target:
            entity_id: input_select.my_blind_4pos_selector
          data:
              option: "Close" # 0
        stop_cover:
          action: input_select.select_option
          target:
            entity_id: input_select.my_blind_4pos_selector
          data:
              option: "Stop" # 5
        set_cover_position: # Used to trigger 'My' or 'Favourite' position in Somfy
          action: input_select.select_option
          target:
            entity_id: input_select.my_blind_4pos_selector
          data:
              #option: "{{position}}" # This works for normal blinds, but not via Somfy RTS, only pre-sets allowed
              option: "Favourite" # 1 # This is handy, any position asked for, other than open or closed, will always set '1', which triggers 'My' or 'Favourite' position in Somfy

      #Next blind here.....
```

Example code offered as-is - it works for me to control via Amazon Alexa 🙂. There are probably neater ways to write it, maybe using variables instead of repeating the entity names multiple times etc...

Also for 'Homekit' specifically, I found it was terrible at doing the positional control. It seems to never issue actual Open/Close commands, but instead sends the levels 0 and 100, which won't work for these kinds of blinds. The UI feedback in Homekit was also really slow and usually out of sync... Best to just not use it, so just remove the section in the YAML for 'set_cover_position' piece... If you omit that, it just becomes a simple Up/Down blind and plays nice with homekit.
